--
-- PostgreSQL database dump
--

\restrict PZlab52O4j2pZCH65eUiOCsdm7E5vU3ajTB0jQg8tLavJO1dwRyetw4TbC4TrYf

-- Dumped from database version 18.0
-- Dumped by pg_dump version 18.0

-- Started on 2026-03-12 17:56:49

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 220 (class 1259 OID 41044)
-- Name: tasks; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tasks (
    created_at timestamp(6) without time zone,
    id bigint NOT NULL,
    description character varying(255),
    status character varying(255),
    title character varying(255) NOT NULL,
    CONSTRAINT tasks_status_check CHECK (((status)::text = ANY ((ARRAY['TODO'::character varying, 'IN_PROGRESS'::character varying, 'DONE'::character varying])::text[])))
);


ALTER TABLE public.tasks OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 41043)
-- Name: tasks_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.tasks ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tasks_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 4961 (class 0 OID 41044)
-- Dependencies: 220
-- Data for Name: tasks; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.tasks (created_at, id, description, status, title) FROM stdin;
2026-03-08 22:13:11.349042	1	lire le coran au minimum une fois par journée	IN_PROGRESS	lecture du Coran
2026-03-08 22:14:36.724594	2	Effectuer les 5 prières quotidiennes	IN_PROGRESS	La prière
2026-03-10 11:38:38.74777	3	vous avez deux cours aujourd'hui	DONE	Suivre les cours
2026-03-12 17:40:54.878218	6	Vous avez cours de Projet Opérationnel	TODO	Faire cours
\.


--
-- TOC entry 4967 (class 0 OID 0)
-- Dependencies: 219
-- Name: tasks_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.tasks_id_seq', 6, true);


--
-- TOC entry 4812 (class 2606 OID 41053)
-- Name: tasks tasks_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tasks
    ADD CONSTRAINT tasks_pkey PRIMARY KEY (id);


-- Completed on 2026-03-12 17:56:49

--
-- PostgreSQL database dump complete
--

\unrestrict PZlab52O4j2pZCH65eUiOCsdm7E5vU3ajTB0jQg8tLavJO1dwRyetw4TbC4TrYf

